-- Drop tables
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS company CASCADE;
DROP TABLE IF EXISTS company_socials CASCADE;
DROP TABLE IF EXISTS shops CASCADE;
DROP TABLE IF EXISTS shop_phones CASCADE;
DROP TABLE IF EXISTS shop_worktimes CASCADE;
DROP TABLE IF EXISTS coffee CASCADE;
DROP TABLE IF EXISTS shop_coffees CASCADE;
DROP TABLE IF EXISTS subscription CASCADE;
drop table if exists transactions cascade;