basePath: /api/v1
definitions:
  auth_request.ConfirmSmsRequest:
    properties:
      code:
        type: integer
      sessionId:
        type: string
    required:
    - code
    - sessionId
    type: object
  auth_request.LoginRequest:
    properties:
      phoneNumber:
        type: string
    required:
    - phoneNumber
    type: object
  auth_request.ResendSmsRequest:
    properties:
      sessionId:
        type: string
    required:
    - sessionId
    type: object
  subscriptions_request.BuySubscriptionRequest:
    properties:
      subscriptionId:
        type: integer
    type: object
  user_request.LogoutRequest:
    type: object
host: 127.0.0.1:8000
info:
  contact:
    email: davronbekov.o@itv.uz
  title: Hoopla | Api
  version: 1.0.0
paths:
  /auth/confirm-sms:
    post:
      consumes:
      - application/json
      parameters:
      - description: Confirm Sms Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth_request.ConfirmSmsRequest'
      produces:
      - application/json
      responses: {}
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth_request.LoginRequest'
      produces:
      - application/json
      responses: {}
      tags:
      - Auth
  /auth/resend-sms:
    post:
      consumes:
      - application/json
      parameters:
      - description: Resend Sms Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth_request.ResendSmsRequest'
      produces:
      - application/json
      responses: {}
      tags:
      - Auth
  /shops/near-shops:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: lat
        required: true
        type: number
      - in: query
        name: long
        required: true
        type: number
      - in: query
        name: name
        type: string
      produces:
      - application/json
      responses: {}
      tags:
      - Shops
  /shops/shop:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: shopId
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      tags:
      - Shops
  /subscriptions:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - Subscriptions
  /subscriptions/buy:
    post:
      consumes:
      - application/json
      parameters:
      - description: Buy Subscription
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/subscriptions_request.BuySubscriptionRequest'
      produces:
      - application/json
      responses: {}
      tags:
      - Subscriptions
  /user/generate-qr-code:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - QR
  /user/get-me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - User
  /user/logout:
    post:
      consumes:
      - application/json
      parameters:
      - description: Logout from an account
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user_request.LogoutRequest'
      produces:
      - application/json
      responses: {}
      tags:
      - User
  /user/orders-list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - User
  /user/refresh-token:
    patch:
      consumes:
      - application/json
      parameters:
      - in: query
        name: refreshToken
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      tags:
      - User
swagger: "2.0"
